# Generated by Django 5.1.15 on 2026-01-14 10:56

import guest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='guest',
            managers=[
                ('objects', guest.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='guest',
            name='username',
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
